export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCT = "GET_PRODUCT"
export const UPDATE_FILTERS = "UPDATE_FILTERS"
export const UPDATE_PANEL = "UPDATE_PANEL"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const ADD_CART = 'ADD_CART' ;
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';