import { containerVariants } from "@/animations/routes"
import { MotionDiv } from "@/components/MotionComponents/MotionComponents"
import Nav from "@/components/Nav/Nav"
import { Montserrat } from "next/font/google"
import "./globals.css"

const montserrat = Montserrat({
  weight: ["400", "500"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Nav />
        <MotionDiv
          className="container"
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          exit="exit"
        >
          {children}
        </MotionDiv>
      </body>
    </html>
  )
}
